### ISSUE TITLE
Notification only happening when opening the application. 

### ISSUE THREAD

**Issue by dikkadev** [arnobk/dupeboard#1]
Title.

If you have  to open the App to make the notification send, it kinda makes the notification useless

**Comment by arnobify** [comment]
Can you please include this following information?
Device model:
Android Version:
ROM name(If you are using any custom rom):
Dupeboard Version:
How often this issue occurs?: 

This will help me to debug your problem as Notification is working fine for everyone else and I haven't got any report like yours.

**Comment by tuft1990** [comment]
Why have I received this response by email when It has nothing to do with me?

**Comment by arnobify** [comment]
As there is not enough information about this problem and no one else reported this issue, I'm closing this issue.

**Comment by MuddyCrayon7434** [comment]
?
